config:
  replacements:
    - registry: quay.io
      repo_mappings:
        rhoai/odh-operator-bundle: rhoai/odh-operator-bundle
        rhoai/odh-rhel9-operator: rhoai/odh-rhel9-operator
        rhoai/odh-ml-pipelines-launcher-rhel9: rhoai/odh-ml-pipelines-launcher-rhel9
        rhoai/odh-ml-pipelines-driver-rhel9: rhoai/odh-ml-pipelines-driver-rhel9
        rhoai/odh-kuberay-operator-controller-rhel9: rhoai/odh-kuberay-operator-controller-rhel9
        rhoai/odh-kf-notebook-controller-rhel9: rhoai/odh-kf-notebook-controller-rhel9
        rhoai/odh-data-science-pipelines-operator-controller-rhel9: rhoai/odh-data-science-pipelines-operator-controller-rhel9
        rhoai/odh-model-controller-rhel9: rhoai/odh-model-controller-rhel9
        rhoai/odh-trustyai-service-operator-rhel9: rhoai/odh-trustyai-service-operator-rhel9
        rhoai/odh-training-operator-rhel9: rhoai/odh-training-operator-rhel9
        rhoai/odh-dashboard-rhel9: rhoai/odh-dashboard-rhel9
        rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9: rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9
        rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9: rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9
        rhoai/odh-data-science-pipelines-argo-argoexec-rhel9: rhoai/odh-data-science-pipelines-argo-argoexec-rhel9
        rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9: rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9
        rhoai/odh-notebook-controller-rhel9: rhoai/odh-notebook-controller-rhel9
        rhoai/odh-mlmd-grpc-server-rhel9: rhoai/odh-mlmd-grpc-server-rhel9
        rhoai/odh-ml-pipelines-api-server-v2-rhel9: rhoai/odh-ml-pipelines-api-server-v2-rhel9
        rhoai/odh-trustyai-service-rhel9: rhoai/odh-trustyai-service-rhel9
        rhoai/odh-model-registry-operator-rhel9: rhoai/odh-model-registry-operator-rhel9
        rhoai/odh-model-registry-rhel9: rhoai/odh-model-registry-rhel9
        rhoai/odh-feast-operator-rhel9: rhoai/odh-feast-operator-rhel9
        rhoai/odh-feature-server-rhel9: rhoai/odh-feature-server-rhel9
        rhoai/odh-llama-stack-k8s-operator-rhel9: rhoai/odh-llama-stack-k8s-operator-rhel9
        rhoai/odh-llm-d-inference-scheduler-rhel9: rhoai/odh-llm-d-inference-scheduler-rhel9
        rhoai/odh-llm-d-routing-sidecar-rhel9: rhoai/odh-llm-d-routing-sidecar-rhel9
        rhoai/odh-must-gather-rhel9: rhoai/odh-must-gather-rhel9
        rhoai/odh-kserve-agent-rhel9: rhoai/odh-kserve-agent-rhel9
        rhoai/odh-kserve-controller-rhel9: rhoai/odh-kserve-controller-rhel9
        rhoai/odh-kserve-router-rhel9: rhoai/odh-kserve-router-rhel9
        rhoai/odh-kserve-storage-initializer-rhel9: rhoai/odh-kserve-storage-initializer-rhel9
        rhoai/odh-ta-lmes-driver-rhel9: rhoai/odh-ta-lmes-driver-rhel9
        rhoai/odh-ta-lmes-job-rhel9: rhoai/odh-ta-lmes-job-rhel9
        rhoai/odh-fms-guardrails-orchestrator-rhel9: rhoai/odh-fms-guardrails-orchestrator-rhel9
        rhoai/odh-trustyai-vllm-orchestrator-gateway-rhel9: rhoai/odh-trustyai-vllm-orchestrator-gateway-rhel9
        rhoai/odh-built-in-detector-rhel9: rhoai/odh-built-in-detector-rhel9
        rhoai/odh-pipeline-runtime-datascience-cpu-py312-rhel9: rhoai/odh-pipeline-runtime-datascience-cpu-py312-rhel9
        rhoai/odh-pipeline-runtime-minimal-cpu-py312-rhel9: rhoai/odh-pipeline-runtime-minimal-cpu-py312-rhel9
        rhoai/odh-pipeline-runtime-pytorch-cuda-py312-rhel9: rhoai/odh-pipeline-runtime-pytorch-cuda-py312-rhel9
        rhoai/odh-pipeline-runtime-pytorch-rocm-py312-rhel9: rhoai/odh-pipeline-runtime-pytorch-rocm-py312-rhel9
        rhoai/odh-pipeline-runtime-tensorflow-cuda-py312-rhel9: rhoai/odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
        rhoai/odh-pipeline-runtime-tensorflow-rocm-py312-rhel9: rhoai/odh-pipeline-runtime-tensorflow-rocm-py312-rhel9
        rhoai/odh-workbench-codeserver-datascience-cpu-py312-rhel9: rhoai/odh-workbench-codeserver-datascience-cpu-py312-rhel9
        rhoai/odh-workbench-jupyter-datascience-cpu-py312-rhel9: rhoai/odh-workbench-jupyter-datascience-cpu-py312-rhel9
        rhoai/odh-workbench-jupyter-minimal-cpu-py312-rhel9: rhoai/odh-workbench-jupyter-minimal-cpu-py312-rhel9
        rhoai/odh-workbench-jupyter-minimal-cuda-py312-rhel9: rhoai/odh-workbench-jupyter-minimal-cuda-py312-rhel9
        rhoai/odh-workbench-jupyter-minimal-rocm-py312-rhel9: rhoai/odh-workbench-jupyter-minimal-rocm-py312-rhel9
        rhoai/odh-workbench-jupyter-pytorch-cuda-py312-rhel9: rhoai/odh-workbench-jupyter-pytorch-cuda-py312-rhel9
        rhoai/odh-workbench-jupyter-pytorch-rocm-py312-rhel9: rhoai/odh-workbench-jupyter-pytorch-rocm-py312-rhel9
        rhoai/odh-workbench-jupyter-tensorflow-cuda-py312-rhel9: rhoai/odh-workbench-jupyter-tensorflow-cuda-py312-rhel9
        rhoai/odh-workbench-jupyter-tensorflow-rocm-py312-rhel9: rhoai/odh-workbench-jupyter-tensorflow-rocm-py312-rhel9
        rhoai/odh-workbench-jupyter-trustyai-cpu-py312-rhel9: rhoai/odh-workbench-jupyter-trustyai-cpu-py312-rhel9
        rhoai/odh-guardrails-detector-huggingface-runtime-rhel9: rhoai/odh-guardrails-detector-huggingface-runtime-rhel9
        rhoai/odh-openvino-model-server-rhel9: rhoai/odh-openvino-model-server-rhel9
        rhoai/odh-vllm-cpu-rhel9: rhoai/odh-vllm-cpu-rhel9
        rhoai/odh-vllm-gaudi-rhel9: rhoai/odh-vllm-gaudi-rhel9
        rhoai/odh-model-registry-job-async-upload-rhel9: rhoai/odh-model-registry-job-async-upload-rhel9
        rhoai/odh-llama-stack-core-rhel9: rhoai/odh-llama-stack-core-rhel9
        rhoai/odh-mod-arch-model-registry-rhel9: rhoai/odh-mod-arch-model-registry-rhel9
        rhoai/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-rhel9: rhoai/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-rhel9
        rhoai/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9: rhoai/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9
        rhoai/odh-model-metadata-collection-rhel9: rhoai/odh-model-metadata-collection-rhel9
        rhoai/odh-mod-arch-gen-ai-rhel9: rhoai/odh-mod-arch-gen-ai-rhel9
        rhoai/odh-kube-auth-proxy-rhel9: rhoai/odh-kube-auth-proxy-rhel9
        rhoai/odh-kube-rbac-proxy-rhel9: rhoai/odh-kube-rbac-proxy-rhel9
        rhoai/odh-model-performance-data-rhel9: rhoai/odh-model-performance-data-rhel9
        rhoai/odh-maas-api-rhel9: rhoai/odh-maas-api-rhel9
        rhoai/odh-training-cuda121-torch24-py311-rhel9: rhoai/odh-training-cuda121-torch24-py311-rhel9
        rhoai/odh-training-cuda124-torch25-py311-rhel9: rhoai/odh-training-cuda124-torch25-py311-rhel9
        rhoai/odh-training-cuda128-torch28-py312-rhel9: rhoai/odh-training-cuda128-torch28-py312-rhel9
        rhoai/odh-training-rocm62-torch24-py311-rhel9: rhoai/odh-training-rocm62-torch24-py311-rhel9
        rhoai/odh-training-rocm62-torch25-py311-rhel9: rhoai/odh-training-rocm62-torch25-py311-rhel9
        rhoai/odh-training-rocm64-torch28-py312-rhel9: rhoai/odh-training-rocm64-torch28-py312-rhel9
        rhoai/odh-trainer-rhel9: rhoai/odh-trainer-rhel9
        rhoai/odh-trustyai-nemo-guardrails-server-rhel9: rhoai/odh-trustyai-nemo-guardrails-server-rhel9
        rhoai/odh-trustyai-garak-lls-provider-dsp-rhel9: rhoai/odh-trustyai-garak-lls-provider-dsp-rhel9
        rhoai/odh-mlflow-rhel9: rhoai/odh-mlflow-rhel9
        rhoai/odh-mlflow-operator-rhel9: rhoai/odh-mlflow-operator-rhel9
        rhoai/odh-mlserver-rhel9: rhoai/odh-mlserver-rhel9
        rhoai/odh-mod-arch-maas-rhel9: rhoai/odh-mod-arch-maas-rhel9
        rhoai/odh-training-rocm64-torch29-py312-rhel9: rhoai/odh-training-rocm64-torch29-py312-rhel9
        rhoai/odh-training-cuda128-torch29-py312-rhel9: rhoai/odh-training-cuda128-torch29-py312-rhel9
        rhoai/odh-eval-hub-rhel9: rhoai/odh-eval-hub-rhel9
        rhoai/odh-spark-operator-rhel9: rhoai/odh-spark-operator-rhel9
        rhoai/odh-cli-rhel9: rhoai/odh-cli-rhel9
        rhoai/odh-workload-variant-autoscaler-controller-rhel9: rhoai/odh-workload-variant-autoscaler-controller-rhel9
        rhoai/odh-maas-controller-rhel9: rhoai/odh-maas-controller-rhel9
        rhoai/odh-th06-cuda130-torch291-py312-rhel9: rhoai/odh-th06-cuda130-torch291-py312-rhel9
        rhoai/odh-th06-rocm64-torch291-py312-rhel9: rhoai/odh-th06-rocm64-torch291-py312-rhel9
        rhoai/odh-th06-cpu-torch291-py312-rhel9: rhoai/odh-th06-cpu-torch291-py312-rhel9
        rhoai/odh-llm-d-kv-cache-rhel9: rhoai/odh-llm-d-kv-cache-rhel9
        rhoai/odh-mod-arch-automl-rhel9: rhoai/odh-mod-arch-automl-rhel9
        rhoai/odh-mod-arch-autorag-rhel9: rhoai/odh-mod-arch-autorag-rhel9
        rhoai/odh-mod-arch-eval-hub-rhel9: rhoai/odh-mod-arch-eval-hub-rhel9
        rhoai/odh-kserve-llmisvc-controller-rhel9: rhoai/odh-kserve-llmisvc-controller-rhel9
        rhoai/odh-mod-arch-mlflow-rhel9: rhoai/odh-mod-arch-mlflow-rhel9
        rhoai/odh-automl-rhel9: rhoai/odh-automl-rhel9
        rhoai/odh-autorag-rhel9: rhoai/odh-autorag-rhel9
        rhoai/odh-ai-gateway-payload-processing-rhel9: rhoai/odh-ai-gateway-payload-processing-rhel9
        rhoai/odh-pipelines-components-rhel9: rhoai/odh-pipelines-components-rhel9
        rhoai/odh-rhaii-validator-tools-rhel9: rhoai/odh-rhaii-validator-tools-rhel9
        rhoai/odh-rhaii-cluster-validator-rhel9: rhoai/odh-rhaii-cluster-validator-rhel9
        rhoai/odh-llm-d-batch-gateway-apiserver-rhel9: rhoai/odh-llm-d-batch-gateway-apiserver-rhel9
        rhoai/odh-llm-d-batch-gateway-processor-rhel9: rhoai/odh-llm-d-batch-gateway-processor-rhel9
        rhoai/odh-llm-d-batch-gateway-gc-rhel9: rhoai/odh-llm-d-batch-gateway-gc-rhel9
        rhoai/odh-model-serving-api-rhel9: rhoai/odh-model-serving-api-rhel9
        rhoai/odh-kserve-autogluon-server-rhel9: rhoai/odh-kserve-autogluon-server-rhel9
        rhoai/odh-ai-fifth-demo-rhel9: rhoai/odh-ai-fifth-demo-rhel9
        rhoai/odh-ai-sixth-demo-rhel9: rhoai/odh-ai-sixth-demo-rhel9
  supported-ocp-versions:
    build:
      - name: v4.19
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.19
      - name: v4.20
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20
      - name: v4.21
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.21
    release:
      - v4.19
      - v4.20
      - v4.21
