name: Instant Merge Bundle Nudges

on:
  pull_request:
    branches:
      - 'rhoai-*'  # Trigger the workflow on pushes to any rhoai-* branch
    types:
      - opened
      - reopened
    paths:
      - bundle/bundle-patch.yaml

env:
  COMPONENT: odh-operator-bundle-v2-

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH=$BRANCH"
          VERSION=v${BRANCH/rhoai-/}
          echo "VERSION=$VERSION"
          SUFFIX=${VERSION/./-}
          echo "SUFFIX=$SUFFIX"
      - name: instant-merge
        if: ${{ github.event.sender.login == 'konflux-internal-p02[bot]' && ( startsWith(github.event.pull_request.title, '$COMPONENT') || contains(github.event.pull_request.title, '$COMPONENT') ) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}