name: Process FBC Fragment
run-name: Process FBC Fragment
on:
  workflow_dispatch:
#    inputs:
#      dry_run:
#        type: boolean
#        description: 'Dry-Run'
#        required: true
#        default: True

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Setup OCM CLI
        env:
          OCM_TOKEN: ${{ secrets.OCM_TOKEN }}
        run: |
          cp bin/ocm /usr/local/bin/ocm
          chmod +x /usr/local/bin/ocm
          ocm login --token="${OCM_TOKEN}"
          ocm list clusters
      - name: Check Status
        env:
          OCM_TOKEN: ${{ secrets.OCM_TOKEN }}
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUD_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUD_SECRET }}
        run: |
          python src/check_instances_status.py