name: Push To Stage
run-name: Push To Stage
on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release Branch'
        required: true
      rhoai_version:
        description: 'Current RHOAI version, eg v2.14.0'
        required: true
      commit:
        description: 'Commit sha of the catalog to be pushed to stage'
        default: ''
permissions:
  contents: write
jobs:
  push-to-stage:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhoai/rhoai-task-toolset:latest
      options: --privileged
    steps:
      - name: Git checkout RBC main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Get Ref
        id: get-ref
        run: |
          ref=${{ github.event.inputs.release_branch }}
          if [[ -n "${{ github.event.inputs.commit }}" ]];
          then
            ref=${{ github.event.inputs.commit }}
            echo "ref=${ref}" >> $GITHUB_OUTPUT
          fi
          echo "ref=$ref"
      - name: Git checkout RBC release
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-ref.outputs.ref }}
          path: ${{ github.event.inputs.release_branch }}
      - name: Git checkout utils
        uses: actions/checkout@v4
        with:
          repository: rhoai-rhtap/RHOAI-Konflux-Automation
          ref: main
          path: utils
      - name: Install dependencies
        run: |
          cd ${{ github.event.inputs.release_branch }}
          git branch
          ls .tekton/